# .github/config.yml
# Configuration for develop branch

# Request-Info Configuration (https://github.com/behaviorbot/request-info)
requestInfoReplyComment: >
  :mag: Please help us improve by sharing additional details about your contribution!
  Our team needs more information to properly review this.

requestInfoDefaultTitles:
  - update
  - fix
  - changes
  - develop branch update

requestInfoLabelToAdd: "Status: Needs Info"

# Welcome Configuration
newIssueWelcomeComment: >
  :seedling: Welcome to our develop branch issue tracker!
  Please ensure you've:
  1. Followed the development checklist
  2. Referenced the correct milestone
  3. Included environment details

newPRWelcomeComment: >
  :construction_worker: Thanks for contributing to our development branch!
  Please verify:
  - All tests pass
  - Documentation updated
  - Branch is up-to-date with develop

# PR Merge Configuration
firstPRMergeComment: >
  :rocket: Amazing work merging your first develop branch PR! 
  The development team (including Zulqurnain) appreciates your contribution!

todo:
  - label: "Stage: Development"
  - label: "Priority: High"
  - label: "Type: Enhancement"