name: Assign PR Author
on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - develop  # Specific to develop branch

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Assign PR Author
        uses: technote-space/assign-author@v1.7.1  # Updated to latest version
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Custom configuration
          allow_self_assign: true
          skip_draft: true      # Skip draft PRs
          add_reviewers: false  # Maintain original behavior